# H2 Database Configuration
spring:
  datasource:
    url: jdbc:h2:mem:restrictionhours
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  # H2 Console (available at http://localhost:8080/h2-console)
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA/Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # CORS Configuration (for frontend integration)
  web:
    cors:
      allowed-origins: 
        - http://localhost:3000
        - http://localhost:5173
      allowed-methods: 
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers: "*"
      allow-credentials: true

# Server Configuration
server:
  port: 8888 